StokOtomasyonu/StokOtomasyonu/Controllers/MusteriController.cs
using StokOtomasyonu.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;

namespace StokOtomasyonu.Controllers
{
    public class MusteriController : Controller
    {
        // GET: Musteri
        VeritabanıEntitiesContainer db = new VeritabanıEntitiesContainer();
        public ActionResult Index(int sayfa=1)
        {
            var musteriList = db.TBLMUSTERILERSet.ToList().ToPagedList(sayfa, 4);
            //List<TBLMUSTERILER> musteriList = db.TBLMUSTERILERSet.ToList();
            return View(musteriList);
        }
        [HttpGet]
        public ActionResult YeniMusteri()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YeniMusteri(TBLMUSTERILER p1)
        {
            if (!ModelState.IsValid)
            {
                return View("YeniMusteri");
            }
            db.TBLMUSTERILERSet.Add(p1);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Sil(int id)
        {
            var musteri = db.TBLMUSTERILERSet.Find(id);
            db.TBLMUSTERILERSet.Remove(musteri);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult MusteriGetir(int id)
        {
            var mus = db.TBLMUSTERILERSet.Find(id);
            return View("MusteriGetir", mus);
        }
        public ActionResult Guncelle(TBLMUSTERILER p1)
        {
            var musteri = db.TBLMUSTERILERSet.Find(p1.MUSTERIID);
            musteri.MUSTERIAD = p1.MUSTERIAD;
            musteri.MUSTERISOYAD = p1.MUSTERISOYAD;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

StokOtomasyonu/StokOtomasyonu/Views/Musteri/Index.cshtml
@using StokOtomasyonu.Models
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<TBLMUSTERILER>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Musteriler</h2>

<table class="table table-bordered" id="tbl1">
    <thead>
        <tr>
            <th>Musteri ID</th>
            <th>Musteri Adi</th>
            <th>Musteri Soyadi</th>
            <th>Sil</th>
            <th>Guncelle</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var mus in Model)
        {
            <tr>
                <th>@mus.MUSTERIID</th>
                <td>@mus.MUSTERIAD</td>
                <td>@mus.MUSTERISOYAD</td>
                <td><a href="/Musteri/Sil/@mus.MUSTERIID" class="btn btn-danger" onclick="return confirm('Silmek istediğinize emin misiniz?')">Sil</a></td>
                <td><a href="/Musteri/MusteriGetir/@mus.MUSTERIID" class="btn btn-success">Guncelle</a></td>
            </tr>
        }
    </tbody>
</table>
@Html.PagedListPager((IPagedList)Model, sayfa => Url.Action("Index", new { sayfa }))
<a href="/Musteri/YeniMusteri/" class="btn btn-primary">Yeni Musteri Ekle</a>

<script type="text/javascript" src="https://cdn.datatables.net/v/bs-3.3.7/jq-2.2.4/jszip-3.1.3/pdfmake-0.1.27/dt-1.10.15/b-1.3.1/b-colvis-1.3.1/b-flash-1.3.1/b-html5-1.3.1/b-print-1.3.1/r-2.1.1/sc-1.4.2/se-1.2.2/datatables.min.js"></script>

<link href="~/Content/DataTables/css/dataTables.bootstrap4.css" rel="stylesheet" />

<script>
    $('#tbl1').dataTable();
</script>

StokOtomasyonu/StokOtomasyonu/Views/Musteri/MusteriGetir.cshtml
@model StokOtomasyonu.Models.TBLMUSTERILER
@{
    ViewBag.Title = "MusteriGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>MusteriGetir</h2>

@using (Html.BeginForm("Guncelle", "Musteri", FormMethod.Post))
{
<div class="form-group">
    @Html.LabelFor(m => m.MUSTERIID)
    @Html.TextBoxFor(m => m.MUSTERIID, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.MUSTERIAD)
    @Html.TextBoxFor(m => m.MUSTERIAD, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.MUSTERISOYAD)
    @Html.TextBoxFor(m => m.MUSTERISOYAD, new { @class = "form-control" })
</div>
<div>
    <button class="btn btn-warning">Musteri Guncelle</button>
</div>
}

StokOtomasyonu/StokOtomasyonu/Views/Musteri/YeniMusteri.cshtml
@model StokOtomasyonu.Models.TBLMUSTERILER
@{
    ViewBag.Title = "YeniMusteri";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>YeniMusteri</h2>

<form method="post" class="form-group">
    <div>
        <label>Musteri Adi</label>
        @Html.TextBoxFor(m => m.MUSTERIAD, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.MUSTERIAD, "", new { @style = "color:orange" })
    </div>
    <div>
        <label>Musteri Soyadi</label>
        <input type="text" class="form-control" name="MUSTERISOYAD" />
    </div>
    <div style="margin-top:10px">
        <button class="btn btn-info" id="btn1">Musteri Ekle</button>
    </div>
    <script>
        $('#btn1').click(function () {
            alert('Musteri Eklendi.')
        });
    </script>
</form>