StokOtomasyonu/StokOtomasyonu/Controllers/UrunlerController.cs
using StokOtomasyonu.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;

namespace StokOtomasyonu.Controllers
{
    public class UrunlerController : Controller
    {
        // GET: Urunler
        VeritabanıEntitiesContainer db = new VeritabanıEntitiesContainer();
        public ActionResult Index(int sayfa=1)
        {

            var degerler = db.TBLURUNLERSet.ToList().ToPagedList(sayfa, 8);
            return View(degerler);
        }
        [HttpGet]
        public ActionResult UrunEkle()
        {
            List<SelectListItem> degerler = (from i in db.TBLKATEGORILERSet.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = i.KATEGORIAD,
                                                 Value = i.KATEGORIID.ToString()
                                             }).ToList();
            ViewBag.dgr = degerler;
            return View();
        }
        [HttpPost]
        public ActionResult UrunEkle(TBLURUNLER p1)
        {
            //var ktg = db.TBLKATEGORILERSet.Where(m => m.KATEGORIID == p1.URUNKATEGORI).FirstOrDefault();
            
            db.TBLURUNLERSet.Add(p1);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Sil(int id)
        {
            var urun = db.TBLURUNLERSet.Find(id);
            db.TBLURUNLERSet.Remove(urun);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult UrunGetir(int id)
        {
            var urun = db.TBLURUNLERSet.Find(id);
            return View("UrunGetir", urun);
        }
        public ActionResult Guncelle(TBLURUNLER p)
        {
            var urun = db.TBLURUNLERSet.Find(p.URUNID);
            urun.URUNAD = p.URUNAD;
            urun.MARKA = p.MARKA;
            urun.STOK = p.STOK;
            urun.FIYAT = p.FIYAT;
            urun.URUNKATEGORI = p.URUNKATEGORI;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

StokOtomasyonu/StokOtomasyonu/Views/Urunler/Index.cshtml
@using StokOtomasyonu.Models
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<TBLURUNLER>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Urunler listesi</h2>

<table id="tbl1" class="table table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>Urun Adi</th>
            <th>Kategori</th>
            <th>Marka</th>
            <th>Fiyat</th>
            <th>Stok</th>
            <th>Sil</th>
            <th>Guncelle</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var urun in Model)
        {
            <tr>
                <th>@urun.URUNID</th>
                <td>@urun.URUNAD</td>
                <td>@urun.URUNKATEGORI</td>
                <td>@urun.MARKA</td>
                <td>@urun.FIYAT</td>
                <td>@urun.STOK</td>
                <td><a href="/Urunler/Sil/@urun.URUNID" class="btn btn-danger" onclick="return confirm('Silmek istediğinize emin misiniz?')">Sil</a></td>
                <td><a href="/Urunler/UrunGetir/@urun.URUNID" class="btn btn-success">Guncelle</a></td>
            </tr>
        }
    </tbody>
</table>
@Html.PagedListPager((IPagedList)Model, sayfa => Url.Action("Index", new { sayfa }))
<a href="/Urunler/UrunEkle/" class="btn btn-primary">Yeni Urun Ekle</a>

<script type="text/javascript" src="https://cdn.datatables.net/v/bs-3.3.7/jq-2.2.4/jszip-3.1.3/pdfmake-0.1.27/dt-1.10.15/b-1.3.1/b-colvis-1.3.1/b-flash-1.3.1/b-html5-1.3.1/b-print-1.3.1/r-2.1.1/sc-1.4.2/se-1.2.2/datatables.min.js"></script>

<link href="~/Content/DataTables/css/dataTables.bootstrap4.css" rel="stylesheet" />

<script>
    $('#tbl1').dataTable();
</script>

StokOtomasyonu/StokOtomasyonu/Views/Urunler/UrunEkle.cshtml
@model StokOtomasyonu.Models.TBLKATEGORILER
@{
    ViewBag.Title = "UrunEkle";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>UrunEkle</h2>

<form method="post" class="form-group">
    <div>
        <label>Urun Ad</label>
        <input type="text" class="form-control" name="URUNAD" required="" />
    </div>
    <div>
        <label>Marka</label>
        <input type="text" class="form-control" name="MARKA" required="" />
    </div>
    <div>
        <label>Kategori seciniz ( İslemci=1, Anakart=2, Ram=3, Ekran Kartı=4, Sogutma=5, Guc Kaynagi=6 )</label>
        <input type="text" class="form-control" name="URUNKATEGORI" required="" />
    </div>
    <div>
        <label>Fiyat</label>
        <input type="text" class="form-control" name="FIYAT" required="" />
    </div>
    <div>
        <label>Stok Adeti</label>
        <input type="text" class="form-control" name="STOK" required="" />
    </div>
    <div style="margin-top:10px">
        <button class="btn btn-info" id="btn1">Urun Ekle</button>
    </div>
    <script>
        $('#btn1').click(function () {
            alert('Urun Eklendi.')
        });
    </script>
</form>

StokOtomasyonu/StokOtomasyonu/Views/Urunler/UrunGetir.cshtml
@model StokOtomasyonu.Models.TBLURUNLER
@{
    ViewBag.Title = "UrunGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>UrunGetir</h2>

@using (Html.BeginForm("Guncelle", "Urunler", FormMethod.Post))
{
<div class="form-group">
    @Html.LabelFor(m => m.URUNID)
    @Html.TextBoxFor(m => m.URUNID, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.URUNAD)
    @Html.TextBoxFor(m => m.URUNAD, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.MARKA)
    @Html.TextBoxFor(m => m.MARKA, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.URUNKATEGORI)
    @Html.TextBoxFor(m => m.URUNKATEGORI, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.FIYAT)
    @Html.TextBoxFor(m => m.FIYAT, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.STOK)
    @Html.TextBoxFor(m => m.STOK, new { @class = "form-control" })
</div>
    <div>
        <button class="btn btn-warning">Urun Guncelle</button>
    </div>
}